dist: trusty
language: node_js
node_js:
  - '8'
if: (tag AND tag =~ ^v) OR (commit_message =~ ^Merge\spull\srequest\s#) OR (type = pull_request)
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - .travis/before_install.sh
install: yarn --offline
script: lerna run lint
sudo: false
deploy:
  -
    provider: script
    script: "bash ./scripts/deploy.sh"
    skip_cleanup: true
    true:
      tags: true
  -
    provider: script
    script: "bash ./scripts/deploy.sh"
    skip_cleanup: true
    true:
      branch: master
  -
    allow-empty-commit: true
    email: carbon@us.ibm.com
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: pages
    name: carbon-bot
    provider: pages
    skip_cleanup: true
    true:
      tags: true
notifications:
  email: false
